version: '3'

services:
###> doctrine/doctrine-bundle ###
  mysql:
    image: mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: db_order_preview
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pw
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    command: caddy run -config /etc/caddy/Caddyfile.dev
    ports: ['3000:80', '3443:443']
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '123hit456123hit456123hit456123hit456123hit456123hit456'
      MERCURE_SUBSCRIBER_JWT_KEY: '123hit456123hit456123hit456123hit456123hit456123hit456'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://127.0.0.1:8000
        demo false
        debug false
        demo false

    networks:
      - symfony
###< symfony/mercure-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###

networks:
  symfony:
